name: git secrets scan
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  git-secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install git-secrets
        run: |-
          sudo apt update
          sudo apt install -y git git-secrets
      - name: Git secrets scan
        run: |-
          git secrets --register-aws
          git secrets --scan