name: license header check
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  license-check:
    name: license check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install license-header-checker
        run: |-
          mkdir -p /tmp/license-check
          curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash -s -- -b /tmp/license-check
      - name: Run license check
        env:
          LICENSE_FILE: /tmp/license-check/license-header.txt
        run: |-
          sed -n 1,12p .projenrc.js > $LICENSE_FILE && cat $LICENSE_FILE
          /tmp/license-check/license-header-checker -a -r -i node_modules,cdk.out,coverage $LICENSE_FILE . ts tsx js java
          ([[ -z `git status -s` ]] || (echo "Found files violdate with license header" && exit 1))
