name: test build dist
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test build dist
        run: |-
          chmod +x ./deployment/test-build-dist-1.sh
          ./deployment/test-build-dist-1.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: templates
          path: deployment/global-s3-assets
